### ISSUE TITLE
issue 1: User can see their car

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a html css and script file
- [x]  Add a car to the HTML file
- [x]  style background and car
