### ISSUE TITLE
Issue 2: User can turn their car 

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] query DOM for the car 
- [x] Create a data model that includes which way the car is facing, (north, south, east,  or west)
- [x] Listen for 'keydown' events on the document. 
- [x] create css classes to handle rotation (transform)
- [x] rotate car on up keydown
- [x] rotate car on down keydown
- [x] rotate car on left keydown
- [x] rotate car on right keydown
- [x] clean up css/and any unnecessary html 
- [x] fix all errors
