### ISSUE TITLE
issue-3: User can start their car. 

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x]  add location property to the data model 
- [x] change the car position to absolute so that it can move
- [x] Use the style property of element objects to change your car's top and left box offset styles.
- [x] start interval for every 16 milliseconds 
- [x] clean up any unnecessary css or html
- [x] fix any errors
