### ISSUE TITLE
issue 4: user can stop their car

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x]  Add a boolean to your data model to indicate whether or not the car is started 
- [x] add property to data model to track whether or not the car is stopped or started 
- [x] clean up any unnecessary html or css
- [x] fix any errors
