### ISSUE TITLE
issue 5: user can steer their car

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] add conditional to drive function
- [x] edit condition so east adds to the left property 
- [x] edit condition so west facing subtracts from the left property 
- [x] edit condition so south, adds to top property
- [x] edit condition so if car is facing north, subtract from top property
- [x] test game functionality 
- [x] clean up any css or html 
- [x] check for errors in code 
- [x] fix anything that doesn't contribute to the functionality of the game.
